server:
  name: "project-api"
  addr: "127.0.0.1:8080"
zap:
  DebugFileName: "G:\\Go\\wh_project\\logs\\debug\\project-debug.log"
  InfoFileName:  "G:\\Go\\wh_project\\logs\\info\\project-info.log"
  WarnFileName:  "G:\\Go\\wh_project\\logs\\error\\project-error.log"
  MaxSize: 500
  MaxAge: 28
  MaxBackups: 3
etcd:
  addrs:
    - "127.0.0.1:2379"