server:
  name: "project-user"
  addr: "127.0.0.1:8080"
zap:
  DebugFileName: "G:\\Go\\wh_project\\logs\\debug\\project-debug.log"
  InfoFileName:  "G:\\Go\\wh_project\\logs\\info\\project-info.log"
  WarnFileName:  "G:\\Go\\wh_project\\logs\\error\\project-error.log"
  MaxSize: 500
  MaxAge: 28
  MaxBackups: 3
redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
