server:
  name: "project-project"
  addr: "127.0.0.1:8081"
zap:
  DebugFileName: "G:\\Go\\wh_project\\logs\\debug\\project-debug.log"
  InfoFileName:  "G:\\Go\\wh_project\\logs\\info\\project-info.log"
  WarnFileName:  "G:\\Go\\wh_project\\logs\\error\\project-error.log"
  MaxSize: 500
  MaxAge: 28
  MaxBackups: 3
redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
grpc:
  addr: "127.0.0.1:8882"
  name: "project"
  version: "1.0.0"
  weight: 2
etcd:
  addrs:
    - "127.0.0.1:2379"
mysql:
  username: root
  password: "Gwh0416."
  host: "127.0.0.1"
  port: 3309
  db: whproject
jwt:
  accessExp: 2
  refreshExp: 14
  accessSecret: whproject
  refreshSecret: wh_project